import type { Dictionary } from './fr';

export const de: Dictionary = {
  meta: { title: 'Amareine — Genuss zum Teilen, die Seele der Levante', description: 'Entdecken Sie die syrisch-libanesischen Brote und süßen Spezialitäten von Amareine, hergestellt in Frankreich. Aleppo-Brot, Kaak, Maamoul und mehr für Privatkunden und Gastronomie.' },
  nav: { home: 'Startseite', products: 'Unsere Produkte', story: 'Unser Handwerk', professionals: 'Für Geschäftskunden', contact: 'Kontakt', language: 'Sprache wählen', open: 'Menü öffnen', close: 'Menü schließen', skip: 'Zum Inhalt springen' },
  announcement: 'Die Seele der Levante. Handwerk aus Frankreich.',
  hero: { eyebrow: 'SYRISCH-LIBANESISCHE BÄCKEREI · HERGESTELLT IN FRANKREICH', title: 'Genuss zum Teilen.', accent: 'Die Seele der Levante.', description: 'Brote, die verbinden, und Rezepte, die Generationen überdauern. Bringen Sie die Herzlichkeit syrisch-libanesischer Traditionen an Ihren Tisch.', primary: 'Unsere Produkte entdecken', secondary: 'Unsere Geschichte', note: 'Eine Geschichte von Brot. Und vom Miteinander.', imageAlt: 'Goldbraune Fladenbrote auf einem Tisch gestapelt', stamp: 'Einfach gemeinsam genießen', scroll: 'Hier beginnt der Genuss' },
  values: [ { title: 'Syrisch-libanesische Wurzeln', text: 'Rezepte voller Geschichte' }, { title: 'Hergestellt in Frankreich', text: 'Unser Handwerk in Folschviller' }, { title: 'Freude am Teilen', text: 'Für jeden Tisch' } ],
  catalog: { eyebrow: 'GENUSS, DER VERBINDET', title: 'Für jeden Geschmack', accent: 'ein Stück Amareine.', description: 'Vom täglichen Brot bis zu süßen Köstlichkeiten für besondere Anlässe: Entdecken Sie unser Sortiment.', all: 'Alle Produkte', bread: 'Brote', sweet: 'Süße Spezialitäten', search: 'Produkt suchen', empty: 'Keine Produkte entsprechen Ihrer Suche.', reset: 'Alle Produkte anzeigen', view: 'Entdecken', back: 'Zurück zu den Produkten', details: 'Über dieses Produkt', serving: 'Ideen für Ihren Tisch', ask: 'Mehr zu diesem Produkt erfahren', note: 'Informationen zu Zutaten, Allergenen, Formaten und Verfügbarkeit erhalten Sie bei unserem Team. Die Fotos dienen der Veranschaulichung.', count: 'Produkte' },
  products: [
    { id: 'pain-alepin', category: 'bread', name: 'Aleppo-Brot', tag: 'DER KLASSIKER', description: 'Ein weiches Fladenbrot, das zur syrisch-libanesischen Esskultur gehört.', details: 'Als Begleiter im Alltag bringt Aleppo-Brot Aromen und Menschen zusammen. Dank seiner weichen, biegsamen Beschaffenheit eignet es sich zum Teilen ebenso wie zum Füllen.', serving: 'Leicht erwärmen und gemeinsam mit Hummus, Mezze oder gegrilltem Gemüse genießen.' },
    { id: 'pain-orge', category: 'bread', name: 'Gerstenbrot', tag: 'GESCHMACK MIT TRADITION', description: 'Eine weitere Facette unserer Backtradition, die Abwechslung auf den Tisch bringt.', details: 'Gerstenbrot bereichert das Sortiment von Amareine mit seinem eigenen Charakter. Es passt zu einfachen Mahlzeiten ebenso wie zu einer reich gedeckten Tafel.', serving: 'Zu Salat, Suppe oder einer Auswahl an Aufstrichen servieren.' },
    { id: 'kaak', category: 'sweet', name: 'Kaak mit Sesam', tag: 'EINE KNUSPRIGE AUSZEIT', description: 'Eine Sesamspezialität für eine genussvolle Pause.', details: 'Kaak gehören zu den Spezialitäten, die gesellige Momente in der Levante begleiten. Eine Einladung, sich Zeit zu nehmen und eine kleine Köstlichkeit zu genießen.', serving: 'Mit Tee oder Kaffee servieren, zum Frühstück oder für eine Pause zwischendurch.' },
    { id: 'maamoul', category: 'sweet', name: 'Maamoul', tag: 'SÜSSES ZUM VERSCHENKEN', description: 'Ein traditionelles Gebäck, das jedes Treffen zu etwas Besonderem macht.', details: 'Maamoul stehen für festliche Momente und Gastfreundschaft. Sie bringen die süßen Backtraditionen der Levante an Ihren Tisch. Fragen Sie uns nach den verfügbaren Sorten.', serving: 'Auf einem Gebäckteller anrichten und mit Ihren Liebsten genießen.' },
    { id: 'croissant', category: 'sweet', name: 'Sesamcroissant', tag: 'FÜR EINEN GUTEN MORGEN', description: 'Ein Gebäck mit Sesam für einen genussvollen Start in den Tag.', details: 'Auch feines Frühstücksgebäck wie das Croissant mit Sesamsamen gehört zu unserem Sortiment. Hier treffen vertraute Frühstückstraditionen auf die Aromen unserer Bäckerei.', serving: 'Zum Frühstück, Brunch oder zu einer Tasse Kaffee genießen.' },
    { id: 'pain-sandwich', category: 'bread', name: 'Sandwichbrot mit Sesam', tag: 'NACH HERZENSLUST BELEGEN', description: 'Der Begleiter für Ihre Sandwiches und großzügig belegten Kreationen.', details: 'Unser Sandwichbrot mit Sesamsamen bietet Platz für Ihre Lieblingsfüllungen. Es eignet sich für Mahlzeiten im Alltag ebenso wie für die Gastronomie.', serving: 'Mit Gemüse, Käse oder Ihren Lieblingszutaten füllen.' }
  ],
  story: { eyebrow: 'VON UNSEREN WURZELN AN IHREN TISCH', title: 'Brot wird gebacken.', accent: 'Tradition weitergegeben.', intro: 'Manche Aromen verbinden uns über Grenzen und Generationen hinweg.', text: 'Bei Amareine halten wir die syrisch-libanesische Brotkultur in Frankreich lebendig. Unser Anspruch: den großzügigen Charakter überlieferter Rezepte bewahren und unsere Erfahrung und Sorgfalt einbringen.', closing: 'Vom ersten Bissen bis zum letzten geteilten Stück wird jeder Tisch zu einem Ort der Begegnung.', link: 'Sprechen wir über Ihre Wünsche', imageAlt: 'Die Hände eines Bäckers beim Bearbeiten eines bemehlten Teigs', caption: 'Handgriffe. Leidenschaft. Eine Geschichte zum Teilen.' },
  professional: { eyebrow: 'GEMEINSAM WACHSEN', title: 'Ihr Geschäft.', accent: 'Unser Handwerk.', text: 'Gastronomie, Lebensmittelhandel und Vertrieb: Bereichern Sie Ihr Angebot mit den Aromen der Levante.', items: [ 'Ein Sortiment für Ihr Angebot', 'Direkter Austausch mit unserem Team', 'Formate und Verfügbarkeit auf Anfrage' ], button: 'Partner werden', imageAlt: 'Brote während der Herstellung in einer Bäckerei', region: 'VON FRANKREICH AUS MIT IHNEN VERBUNDEN', regionText: 'Sie möchten Amareine vertreiben oder unsere Produkte in Ihrer Nähe finden? Kontaktieren Sie uns, um mehr über die Möglichkeiten in Ihrer Region zu erfahren.' },
  contact: { eyebrow: 'LASSEN SIE UNS INS GESPRÄCH KOMMEN', title: 'Gute Geschichten', accent: 'beginnen mit einem Hallo.', text: 'Eine Frage, ein Wunsch oder ein Vorhaben? Unser Team freut sich auf Ihre Nachricht.', phone: 'Rufen Sie uns an', email: 'Schreiben Sie uns', location: 'Hier finden Sie uns', name: 'Ihr Name', emailLabel: 'Ihre E-Mail-Adresse', company: 'Ihr Unternehmen (optional)', subject: 'Ihr Anliegen', subjects: ['Produktinformationen', 'Partner werden', 'Verkaufsstelle finden', 'Sonstiges Anliegen'], message: 'Ihre Nachricht', placeholder: 'Erzählen Sie uns von Ihren Wünschen oder Ihrem Vorhaben …', consent: 'Ich bin damit einverstanden, dass meine Angaben zur Beantwortung meiner Anfrage verwendet werden.', privacyLink: 'Datenschutz', submit: 'Nachricht senden', sending: 'Wird gesendet …', success: 'Vielen Dank! Ihre Nachricht wurde übermittelt. Unser Team wird sich bei Ihnen melden.', error: 'Die Nachricht konnte nicht gesendet werden. Bitte versuchen Sie es erneut oder kontaktieren Sie uns direkt per E-Mail.', fallback: 'Sie nutzen lieber Ihr E-Mail-Programm?', emailAction: 'E-Mail an uns schreiben', required: 'Mit * gekennzeichnete Felder sind Pflichtfelder.' },
  footer: { description: 'Die Seele der Levante, Handwerk aus Frankreich. Brote und süße Spezialitäten, die Menschen zusammenbringen.', explore: 'Entdecken', follow: 'In Verbindung bleiben', location: 'Folschviller, Frankreich', rights: 'Alle Rechte vorbehalten.', privacy: 'Datenschutz', signature: 'Gutes Brot bringt uns zusammen.' },
  privacy: { title: 'Datenschutz', intro: 'Auf dieser Seite erfahren Sie, wie die über diese Website übermittelten Angaben verwendet werden.', sections: [ { title: 'Ihre Kontaktanfragen', text: 'Der angegebene Name, die E-Mail-Adresse, der optionale Unternehmensname und Ihre Nachricht werden zur Bearbeitung Ihrer Anfrage verwendet. Bitte übermitteln Sie keine sensiblen Informationen. Bei Fragen zu Ihren Angaben schreiben Sie an amareine.europe@gmail.com.' }, { title: 'Übermittlung des Kontaktformulars', text: 'Nachrichten werden über Formspree übermittelt, einen bereits von Amareine genutzten Dienst. Dieser Anbieter erhält die Formulardaten, um Ihre Nachricht zuzustellen. Sie können uns auch direkt per E-Mail oder telefonisch kontaktieren.' }, { title: 'Nutzung der Website und externe Dienste', text: 'Die Website setzt keine Werbecookies und verwendet keine Tools zur Reichweitenmessung. Dienste sozialer Netzwerke und Kartendienste werden erst geladen, wenn Sie die entsprechenden Links öffnen. Der Hostinganbieter kann technische Daten verarbeiten, die für die Sicherheit und den Betrieb der Website erforderlich sind.' } ] },
  notFound: { title: 'Diese Seite ist nicht mehr am Tisch.', text: 'Entdecken Sie unsere Produkte und unsere Geschichte über die Startseite.', button: 'Zur Startseite' }
};
