import type { Dictionary } from './fr';

export const en: Dictionary = {
  meta: { title: 'Amareine — Made for sharing, inspired by the Levant', description: 'Discover Amareine’s Syrian-Lebanese breads and sweet treats, made in France. Aleppo bread, kaak, maamoul and specialities for your table and your business.' },
  nav: { home: 'Home', products: 'Our products', story: 'Our craft', professionals: 'For professionals', contact: 'Contact', language: 'Choose your language', open: 'Open menu', close: 'Close menu', skip: 'Skip to content' },
  announcement: 'The soul of the Levant. Crafted in France.',
  hero: { eyebrow: 'SYRIAN-LEBANESE BAKERY · MADE IN FRANCE', title: 'Made for sharing.', accent: 'Inspired by the Levant.', description: 'Generous breads and recipes passed down through generations. Bring the warmth of Syrian-Lebanese traditions to your table.', primary: 'Discover our products', secondary: 'Our story', note: 'A story of bread. A story of connection.', imageAlt: 'Golden flatbreads stacked on a table', stamp: 'Simply made to share', scroll: 'Good things start here' },
  values: [ { title: 'Syrian-Lebanese roots', text: 'Recipes with a rich history' }, { title: 'Made in France', text: 'Our craft, here in Folschviller' }, { title: 'The joy of sharing', text: 'A place at every table' } ],
  catalog: { eyebrow: 'A TASTE OF GENEROSITY', title: 'For every craving,', accent: 'there’s Amareine.', description: 'From everyday bread to treats for special occasions, explore our range.', all: 'All products', bread: 'Breads', sweet: 'Sweet treats', search: 'Search for a product', empty: 'No products match your search.', reset: 'View all products', view: 'Discover', back: 'Back to products', details: 'About this product', serving: 'Ideas for your table', ask: 'Ask about this product', note: 'For ingredients, allergens, sizes and availability, please contact our team. Photographs are illustrative.', count: 'products' },
  products: [
    { id: 'pain-alepin', category: 'bread', name: 'Aleppo bread', tag: 'THE EVERYDAY CLASSIC', description: 'Soft flatbread at the heart of Syrian-Lebanese meals.', details: 'An everyday companion, Aleppo bread brings flavours and people together. Its soft, flexible texture makes it equally suited to sharing or filling with your favourite ingredients.', serving: 'Warm gently and share with hummus, mezze or grilled vegetables.' },
    { id: 'pain-orge', category: 'bread', name: 'Barley bread', tag: 'A TASTE OF TRADITION', description: 'Another side of our baking tradition, bringing variety to your table.', details: 'Barley bread adds its own character to the Amareine range. It is at home with simple everyday meals and generous spreads alike.', serving: 'Serve with a salad, soup or a selection of dips and spreads.' },
    { id: 'kaak', category: 'sweet', name: 'Sesame kaak', tag: 'A CRUNCHY LITTLE BREAK', description: 'A sesame speciality to enjoy during a delicious break.', details: 'Kaak are part of the Levant’s tradition of gathering and sharing. An invitation to slow down and enjoy a little treat.', serving: 'Serve with tea or coffee, at breakfast or whenever you take a break.' },
    { id: 'maamoul', category: 'sweet', name: 'Maamoul', tag: 'SWEETNESS TO SHARE', description: 'A traditional pastry that makes every gathering an occasion.', details: 'A symbol of celebration and hospitality, maamoul bring the pastry traditions of the Levant to your table. Contact us to discover the varieties available.', serving: 'Arrange on a platter of sweet treats and enjoy with the people you love.' },
    { id: 'croissant', category: 'sweet', name: 'Sesame croissant', tag: 'A MORNING FAVOURITE', description: 'A sesame pastry for a delicious start to the day.', details: 'Our range also includes pastries such as the sesame croissant. A meeting of familiar breakfast favourites and the flavours of our bakery.', serving: 'Enjoy at breakfast, brunch or with a cup of coffee.' },
    { id: 'pain-sandwich', category: 'bread', name: 'Sesame sandwich bread', tag: 'FILL IT YOUR WAY', description: 'A companion for your sandwiches and generously filled creations.', details: 'Made to hold your favourite fillings, our sesame sandwich bread suits both everyday meals and professional catering.', serving: 'Fill with vegetables, cheese or your favourite combination of ingredients.' }
  ],
  story: { eyebrow: 'FROM OUR ROOTS TO YOUR TABLE', title: 'Bread is made.', accent: 'Tradition is passed on.', intro: 'Some flavours bring us together, across borders and generations.', text: 'At Amareine, we keep the culture of Syrian-Lebanese bread alive here in France. Our ambition is to capture the generosity of recipes handed down through generations, adding our experience and care to every step.', closing: 'From the first bite to the last piece shared, every table becomes a place to connect.', link: 'Tell us what you have in mind', imageAlt: 'A baker’s hands working flour-dusted dough', caption: 'A craft. A passion. A story to share.' },
  professional: { eyebrow: 'LET’S GROW TOGETHER', title: 'Your business.', accent: 'Our craft.', text: 'Restaurants, grocers and distributors: bring the flavours of the Levant to your customers.', items: [ 'A range to complement your selection', 'Direct contact with our team', 'Sizes and availability on request' ], button: 'Become a partner', imageAlt: 'Bread being made in a bakery', region: 'BASED IN FRANCE, READY TO CONNECT', regionText: 'Would you like to distribute Amareine or find our products near you? Contact us to explore the options in your area.' },
  contact: { eyebrow: 'LET’S TALK', title: 'Good stories', accent: 'start with hello.', text: 'A question, an idea or a project? Our team is here to listen.', phone: 'Call us', email: 'Write to us', location: 'Find us', name: 'Your name', emailLabel: 'Your email', company: 'Your company (optional)', subject: 'Your enquiry', subjects: ['Product information', 'Become a partner', 'Find a stockist', 'Other enquiry'], message: 'Your message', placeholder: 'Tell us what you have in mind…', consent: 'I agree to my information being used to respond to my enquiry.', privacyLink: 'Privacy', submit: 'Send my message', sending: 'Sending…', success: 'Thank you! Your message has been sent. Our team will get back to you.', error: 'Your message could not be sent. Please try again or contact us directly by email.', fallback: 'Prefer to use your email app?', emailAction: 'Send us an email', required: 'Fields marked with an * are required.' },
  footer: { description: 'The soul of the Levant, crafted in France. Breads and sweet treats that bring people together.', explore: 'Explore', follow: 'Stay in touch', location: 'Folschviller, France', rights: 'All rights reserved.', privacy: 'Privacy', signature: 'Good bread brings us closer.' },
  privacy: { title: 'Privacy', intro: 'This page explains how information submitted through this website is used.', sections: [ { title: 'Your contact enquiries', text: 'The name, email address, optional company name and message you provide are used to handle your enquiry. Please do not send sensitive information. For questions about your information, write to amareine.europe@gmail.com.' }, { title: 'Sending the contact form', text: 'Messages are sent through Formspree, a service already used by Amareine. This provider receives the information in the form to deliver your message. You can also contact us directly by email or phone.' }, { title: 'Browsing and external services', text: 'This website does not set advertising cookies or use audience analytics tools. Social media and map services are only loaded when you open their links. The hosting provider may process technical data needed to keep the website secure and running.' } ] },
  notFound: { title: 'This page has left the table.', text: 'Find our products and discover our story from the home page.', button: 'Back to home' }
};
