export const fr = {
  meta: { title: 'Amareine — Le goût du partage, l’âme du Levant', description: 'Découvrez les pains syro-libanais et les douceurs Amareine, fabriqués en France. Pain alepin, kaak, maamoul et spécialités pour particuliers et professionnels.' },
  nav: { home: 'Accueil', products: 'Nos produits', story: 'Notre savoir-faire', professionals: 'Professionnels', contact: 'Contact', language: 'Choisir la langue', open: 'Ouvrir le menu', close: 'Fermer le menu', skip: 'Aller au contenu' },
  announcement: 'L’âme du Levant. Le savoir-faire français.',
  hero: { eyebrow: 'BOULANGERIE SYRO-LIBANAISE · FABRIQUÉ EN FRANCE', title: 'Le goût du partage.', accent: 'L’âme du Levant.', description: 'Des pains généreux, des recettes qui traversent les générations. Retrouvez à votre table toute la chaleur des traditions syro-libanaises.', primary: 'Découvrir nos produits', secondary: 'Notre histoire', note: 'Une histoire de pain. Une histoire de liens.', imageAlt: 'Pains plats dorés empilés sur une table', stamp: 'À partager, tout simplement', scroll: 'Le plaisir commence ici' },
  values: [ { title: 'Racines syro-libanaises', text: 'Des recettes riches d’histoire' }, { title: 'Fabriqué en France', text: 'Notre savoir-faire à Folschviller' }, { title: 'Le plaisir du partage', text: 'Pour toutes les tables' } ],
  catalog: { eyebrow: 'LA GÉNÉROSITÉ A DU GOÛT', title: 'À chaque envie,', accent: 'son Amareine.', description: 'Du pain du quotidien aux douceurs des grandes occasions, découvrez notre univers.', all: 'Tous les produits', bread: 'Les pains', sweet: 'Les douceurs', search: 'Rechercher un produit', empty: 'Aucun produit ne correspond à votre recherche.', reset: 'Voir tous les produits', view: 'Découvrir', back: 'Retour aux produits', details: 'Autour de ce produit', serving: 'L’inspiration à table', ask: 'Se renseigner sur ce produit', note: 'Pour connaître les ingrédients, les allergènes, les formats et les disponibilités, contactez notre équipe. Les photographies sont des illustrations de présentation.', count: 'produits' },
  products: [
    { id: 'pain-alepin', category: 'bread', name: 'Pain alepin', tag: 'LE GRAND CLASSIQUE', description: 'Un pain plat et moelleux, au cœur des tables syro-libanaises.', details: 'Compagnon des repas du quotidien, le pain alepin réunit les saveurs et les convives. Sa texture souple se prête aussi bien au partage qu’aux préparations garnies.', serving: 'À réchauffer légèrement et à partager avec un houmous, des mezzés ou des légumes grillés.' },
    { id: 'pain-orge', category: 'bread', name: 'Pain d’orge', tag: 'LE GOÛT DE LA TRADITION', description: 'Une autre facette de notre tradition boulangère, pour varier les plaisirs.', details: 'Le pain d’orge enrichit la gamme Amareine d’un caractère singulier. Il trouve sa place dans les repas simples comme dans les tables généreuses.', serving: 'À proposer avec une salade, une soupe ou un assortiment de tartinades.' },
    { id: 'kaak', category: 'sweet', name: 'Kaak au sésame', tag: 'LA PAUSE CROQUANTE', description: 'Une spécialité au sésame, idéale pour accompagner une pause gourmande.', details: 'Les kaak font partie des spécialités qui rythment les moments de convivialité du Levant. Une invitation à prendre son temps autour d’une gourmandise.', serving: 'À servir avec un thé ou un café, au petit-déjeuner ou à l’heure de la pause.' },
    { id: 'maamoul', category: 'sweet', name: 'Maamoul', tag: 'LA DOUCEUR À OFFRIR', description: 'Une pâtisserie traditionnelle qui fait de chaque rencontre une occasion.', details: 'Emblématiques des moments de fête et d’hospitalité, les maamouls invitent les traditions pâtissières du Levant à votre table. Contactez-nous pour découvrir les variétés disponibles.', serving: 'À présenter sur un plateau de douceurs et à savourer avec vos proches.' },
    { id: 'croissant', category: 'sweet', name: 'Croissant au sésame', tag: 'LE RENDEZ-VOUS DU MATIN', description: 'Une viennoiserie au sésame pour commencer la journée avec gourmandise.', details: 'Notre gamme réunit également des viennoiseries, à l’image du croissant aux graines de sésame. Une rencontre entre les habitudes du petit-déjeuner et les saveurs de notre univers.', serving: 'Pour un petit-déjeuner, un brunch ou une pause café.' },
    { id: 'pain-sandwich', category: 'bread', name: 'Pain sandwich au sésame', tag: 'À GARNIR SELON VOS ENVIES', description: 'Le compagnon de vos sandwichs et de vos recettes généreuses.', details: 'Pensé pour accueillir vos garnitures, le pain sandwich aux graines de sésame accompagne les usages du quotidien et les besoins de la restauration.', serving: 'À garnir de légumes, de fromage ou de votre préparation préférée.' }
  ],
  story: { eyebrow: 'DE NOS RACINES À VOTRE TABLE', title: 'Le pain se fabrique.', accent: 'La tradition se transmet.', intro: 'Il y a des saveurs qui nous rassemblent, au-delà des frontières et des générations.', text: 'Chez Amareine, nous faisons vivre la culture du pain syro-libanais depuis la France. Notre ambition : retrouver la générosité des recettes transmises, en y apportant notre expérience et notre envie de bien faire.', closing: 'De la première bouchée au dernier morceau partagé, chaque table devient un lieu de rencontre.', link: 'Parlons de vos envies', imageAlt: 'Les mains d’un boulanger travaillant une pâte farinée', caption: 'Des gestes. Une passion. Une histoire à partager.' },
  professional: { eyebrow: 'GRANDISSONS ENSEMBLE', title: 'Votre métier.', accent: 'Notre savoir-faire.', text: 'Restaurateurs, épiceries, distributeurs : donnons une place aux saveurs du Levant dans votre offre.', items: [ 'Une gamme pour composer votre offre', 'Un échange direct avec notre équipe', 'Des formats et disponibilités sur demande' ], button: 'Devenir partenaire', imageAlt: 'Pains en cours de fabrication dans notre univers boulanger', region: 'DEPUIS LA FRANCE, À VOTRE RENCONTRE', regionText: 'Vous souhaitez distribuer Amareine ou trouver nos produits près de chez vous ? Contactez-nous pour connaître les possibilités dans votre région.' },
  contact: { eyebrow: 'ET SI ON ÉCHANGEAIT ?', title: 'Les belles histoires', accent: 'commencent par un bonjour.', text: 'Une question, une envie, un projet ? Notre équipe est à votre écoute.', phone: 'Appelez-nous', email: 'Écrivez-nous', location: 'Retrouvez-nous', name: 'Votre nom', emailLabel: 'Votre e-mail', company: 'Votre entreprise (facultatif)', subject: 'Votre demande', subjects: ['Informations sur les produits', 'Devenir partenaire', 'Trouver un point de vente', 'Autre demande'], message: 'Votre message', placeholder: 'Parlez-nous de votre envie ou de votre projet…', consent: 'J’accepte que mes informations soient utilisées pour répondre à ma demande.', privacyLink: 'Confidentialité', submit: 'Envoyer mon message', sending: 'Envoi en cours…', success: 'Merci ! Votre message a bien été transmis. Notre équipe reviendra vers vous.', error: 'L’envoi n’a pas abouti. Réessayez ou contactez-nous directement par e-mail.', fallback: 'Vous préférez votre messagerie ?', emailAction: 'Nous écrire par e-mail', required: 'Les champs marqués d’un * sont obligatoires.' },
  footer: { description: 'L’âme du Levant, le savoir-faire français. Des pains et des douceurs faits pour rassembler.', explore: 'À découvrir', follow: 'Restons en lien', location: 'Folschviller, France', rights: 'Tous droits réservés.', privacy: 'Confidentialité', signature: 'Le bon pain rapproche.' },
  privacy: { title: 'Confidentialité', intro: 'Cette page explique comment les informations transmises via ce site sont utilisées.', sections: [ { title: 'Vos demandes de contact', text: 'Le nom, l’adresse e-mail, l’entreprise éventuelle et le message que vous renseignez servent à traiter votre demande. Ne transmettez pas d’informations sensibles. Pour toute question relative à vos informations, écrivez à amareine.europe@gmail.com.' }, { title: 'Transmission du formulaire', text: 'Les messages sont transmis par le service Formspree, déjà utilisé par Amareine. Ce prestataire reçoit les informations du formulaire pour les acheminer. Vous pouvez aussi nous contacter directement par e-mail ou téléphone.' }, { title: 'Navigation et services externes', text: 'Le site n’installe pas de cookies publicitaires ou d’outil de mesure d’audience. Les liens vers les réseaux sociaux et les services de cartographie ne chargent ces services que lorsque vous les ouvrez. L’hébergeur peut traiter des données techniques nécessaires à la sécurité et au fonctionnement du site.' } ] },
  notFound: { title: 'Cette page a quitté la table.', text: 'Retrouvez nos produits et notre univers depuis l’accueil.', button: 'Revenir à l’accueil' }
};

export type Dictionary = typeof fr;
